# <font color ='dark red'> Numpy Randomization of Values and Characters <font>

# <font color='maroon'> Numpy Module Required <font>

In [1]:
import numpy as np

randint,randn,random,seed,uniform,permutation,shuffle,choice

In [2]:
# this generates random numerical float values 
np.random.random()

0.5238287050633746

In [3]:
np.random.random()

0.1787363011719656

In [4]:
# generates float values in (rows,columns)
np.random.randn(5,4)

array([[-2.29579353, -0.07395883,  0.24010518,  0.11973448],
       [ 2.48096733, -0.31867086,  0.04941618, -0.28650085],
       [-1.05639617, -1.40590181,  1.67358717,  0.15333212],
       [ 0.86113455, -1.56446625, -0.31935013, -0.60083001],
       [-0.53732841, -1.50022908, -0.72179477,  0.88985951]])

In [5]:
# generates random integer values with(least value,max value,no. of values to be generated)
np.random.randint(2,30,5)

array([25, 28, 29, 14, 11])

In [6]:
# here the values generated are saved to the number initialized with it and remain same 
np.random.seed(2)
np.random.random()

0.43599490214200376

In [7]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [8]:
# similar to np.random.randint but generated float values
np.random.uniform(2,30,5)

array([ 2.72593449, 17.39054938, 14.18902699, 13.77029846, 11.24937499])

In [9]:
# initialize a list with names of people
names=['Don','Ryan','Aunty','Dalia','Wayne','Ezra','Boyie','Judy','Karis','Joe']

In [10]:
#randomly chooses names(listname,no of names,no repeating names,p=[probabilities of choosing])
np.random.choice(names,3,replace=False,p=[0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1])

array(['Aunty', 'Boyie', 'Dalia'], dtype='<U5')

In [11]:
# craetes an array with numbers that rang from 0 to 19, 20 exclusive
d=np.arange(20)
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
# randomly shuffles the values
np.random.shuffle(d)
d

array([13, 14,  2,  9,  8, 15,  0, 19, 12,  1, 16, 18, 17, 11, 10,  4,  6,
        3,  7,  5])

In [13]:
# also shuffles but considers possibilities
np.random.permutation(d)

array([15,  3,  9, 18,  7, 13,  0,  6,  5, 11,  1, 16,  2, 12, 19, 14,  4,
        8, 17, 10])